input {
 tcp {
   port => 5044
   codec => json
 }
}

filter {
}

output {
 elasticsearch {
   hosts => ["http://elasticsearch:9200"]
   index => "application-logs"
 }

 stdout {
   codec => rubydebug
 }
}
